name: Remove GitHub Links

on:
  workflow_dispatch:   # run manually from Actions tab

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove all GitHub links
        run: |
          # Find & strip GitHub links
          git grep -l 'https://github.com' | grep -v '.github/workflows' | xargs sed -i 's#https://github.com[^ )]*##g'

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated cleanup: removed all GitHub links" || echo "No changes to commit"
          git push
